# Generated by Django 3.1.2 on 2023-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('nameOfPlace', models.CharField(max_length=200)),
                ('totalNoOfSpace', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
