# Generated by Django 3.1.2 on 2023-02-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerShipProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('idPic', models.ImageField(upload_to='')),
                ('proofOfResidence', models.FileField(upload_to='')),
            ],
        ),
    ]
