# Generated by Django 3.1.2 on 2023-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0002_ownershipproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipproof',
            name='idPic',
            field=models.ImageField(max_length=11111111111, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ownershipproof',
            name='img',
            field=models.ImageField(max_length=11111111111, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ownershipproof',
            name='proofOfResidence',
            field=models.FileField(max_length=11111111111, upload_to=''),
        ),
    ]
