# Generated by Django 3.1.2 on 2023-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0004_auto_20230208_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipproof',
            name='idPic',
            field=models.ImageField(blank=True, upload_to='proof'),
        ),
        migrations.AlterField(
            model_name='ownershipproof',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
