# Generated by Django 3.1.2 on 2023-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0005_auto_20230209_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipproof',
            name='idPic',
            field=models.ImageField(upload_to='proof'),
        ),
        migrations.AlterField(
            model_name='ownershipproof',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
