# Generated by Django 3.1.2 on 2023-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0006_auto_20230209_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipproof',
            name='idPic',
            field=models.ImageField(null=True, upload_to='proof'),
        ),
    ]
