# Generated by Django 3.1.2 on 2023-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0007_auto_20230209_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipproof',
            name='idPic',
            field=models.ImageField(null=True, upload_to='proof/images'),
        ),
        migrations.AlterField(
            model_name='ownershipproof',
            name='img',
            field=models.ImageField(upload_to='proof/images'),
        ),
        migrations.AlterField(
            model_name='ownershipproof',
            name='proofOfResidence',
            field=models.FileField(upload_to='proof/documents'),
        ),
    ]
