# Generated by Django 3.1.2 on 2023-02-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturf', '0009_auto_20230209_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipproof',
            name='proofOfResidence',
            field=models.FileField(null=True, upload_to='proof/documents'),
        ),
    ]
